"""Runtime Config Manager Interface (519 PR 2 / D-c1).

OSS-side Protocol for the PRO RuntimeConfigManager singleton. PRO ships
the realized backend behind ``baldur_pro.services.runtime_config``; OSS
callers resolve via ``ProviderRegistry.runtime_config_manager.safe_get()``
and use the returned instance with a None-guard.

Methods are Interface Segregation — only those OSS code currently calls
are declared here. Return types are kept permissive (``Any`` /
``dict[str, Any]``) so this Protocol does not couple to (d)-track types
that have not yet been relocated to OSS.
"""

from __future__ import annotations

from typing import Any, Protocol, runtime_checkable

__all__ = ["RuntimeConfigManager"]


@runtime_checkable
class RuntimeConfigManager(Protocol):
    """Protocol for the PRO runtime configuration manager."""

    def _get_config(self, section: str) -> dict[str, Any]: ...

    def get_config(self, section: str) -> dict[str, Any]: ...

    def get_chaos_config(self) -> dict[str, Any]: ...

    def get_circuit_breaker_config(self) -> dict[str, Any]: ...

    def get_dlq_config(self) -> dict[str, Any]: ...

    def get_error_budget_config(self) -> dict[str, Any]: ...

    def get_governance_config(self) -> dict[str, Any]: ...

    def get_rate_limit_config(self) -> dict[str, Any]: ...

    def get_retry_config(self) -> dict[str, Any]: ...

    def get_all_config(self) -> dict[str, dict[str, Any]]: ...

    def update_with_strategy(self, *args: Any, **kwargs: Any) -> Any: ...

    def get_approval_requests(self, status: str | None = None) -> list[Any]: ...

    def expire_old_requests(self) -> int: ...

    def clear_active_ttl_configs(self) -> None: ...

    def update_chaos_dry_run_config(self, *args: Any, **kwargs: Any) -> Any: ...

    def update_chaos_stop_conditions_config(self, *args: Any, **kwargs: Any) -> Any: ...

    def update_chaos_ttl_config(self, *args: Any, **kwargs: Any) -> Any: ...

    def update_circuit_breaker_config(self, *args: Any, **kwargs: Any) -> Any: ...

    def update_dlq_config(self, *args: Any, **kwargs: Any) -> Any: ...

    def update_retry_config(self, *args: Any, **kwargs: Any) -> Any: ...

    def update_sla_config(self, *args: Any, **kwargs: Any) -> Any: ...

    def update_slo_config(self, *args: Any, **kwargs: Any) -> Any: ...

    def update_rate_limit_config(self, *args: Any, **kwargs: Any) -> Any: ...

    def update_security_config(self, *args: Any, **kwargs: Any) -> Any: ...

    def update_idempotency_config(self, *args: Any, **kwargs: Any) -> Any: ...

    def update_notification_config(self, *args: Any, **kwargs: Any) -> Any: ...

    def update_forensic_config(self, *args: Any, **kwargs: Any) -> Any: ...

    def update_metrics_config(self, *args: Any, **kwargs: Any) -> Any: ...

    def update_error_budget_config(self, *args: Any, **kwargs: Any) -> Any: ...
